name: CI
on:
  pull_request:

jobs:
  CI:
    continue-on-error: true
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Powershell Script
        run: powershell -ExecutionPolicy Bypass -File ci.ps1 -testSettings dropbox-sdk-dotnet\Dropbox.Api.Tests\dropbox.runsettings
        shell: powershell
