name: CI
on:
  pull_request:

jobs:
  DotNetFramework:
    continue-on-error: true
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        # No Need to Setup DotNet, 4.8 comes preinstalled on all runners
      - name: Install Dependencies
        run: dotnet restore dropbox-sdk-dotnet\Dropbox.Api\Dropbox.Api.csproj
      - name: Build
        run: dotnet build dropbox-sdk-dotnet\Dropbox.Api\Dropbox.Api.csproj --configuration Release
